name: Docker CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    #     strategy:
    #       matrix:
    #         node: [14.x, 15.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      #     - name: Setup specific node version
      #       uses: actions/setup-node@main
      #       with:
      #         node-version: ${{matrix.node}}

      - name: Install necessary packages
        run: |
          repo=$(pwd)
          cd ./server
          npm install
          cd $repo

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: doganm95/ewelink-rest-api-server:latest
