name: Publish Docker image

on:
  push:
    paths-ignore:
      - 'README.md'
jobs:
  build-and-push-image:
    name: Build and push docker image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/doganm95/ewelink-rest-api-server:v1.${{ github.run_number }}
            ghcr.io/doganm95/ewelink-rest-api-server:${{ github.sha }}
            ghcr.io/doganm95/ewelink-rest-api-server:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
            org.opencontainers.image.revision=${{ github.sha }}
