name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: List directory
      run: ls -la
      
    - name: Build the Docker image
      run: docker build -f ./docker/Dockerfile . -t doganm95/ewelink-rest-api-server 

#     - name: Run Container
#       run: docker run -p 5000:5000 -e "EWELINK_USERNAME=${{ secrets.EWELINK_USERNAME }}" -e "EWELINK_PASSWORD=" -e "EWELINK_REGION=<your_region>" doganm95/ewelink-rest-api-server

#     - name: Push to Docker Hub
#       uses: docker/build-push-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         repository: my-docker-hub-namespace/my-docker-hub-repository
#         tag_with_ref: true
